// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RiFpwPZc2Ux6gBUCfunxc
// Component: tW2U1fy_zwg8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 5RiFpwPZc2Ux6gBUCfunxc/projectcss
import sty from "./PlasmicDealsContainerLink.module.css"; // plasmic-import: tW2U1fy_zwg8/css

import HotSvgrepoComsvgIcon from "./icons/PlasmicIcon__HotSvgrepoComsvg"; // plasmic-import: PrdEPozKRIsa/icon

createPlasmicElementProxy;

export type PlasmicDealsContainerLink__VariantMembers = {};
export type PlasmicDealsContainerLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicDealsContainerLink__VariantsArgs;
export const PlasmicDealsContainerLink__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDealsContainerLink__ArgsType = {};
type ArgPropType = keyof PlasmicDealsContainerLink__ArgsType;
export const PlasmicDealsContainerLink__ArgProps = new Array<ArgPropType>();

export type PlasmicDealsContainerLink__OverridesType = {
  hotDeals?: Flex__<"a"> & Partial<LinkProps>;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultDealsContainerLinkProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDealsContainerLink__RenderFunc(props: {
  variants: PlasmicDealsContainerLink__VariantsArgs;
  args: PlasmicDealsContainerLink__ArgsType;
  overrides: PlasmicDealsContainerLink__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={PlasmicLink__}
      data-plasmic-name={"hotDeals"}
      data-plasmic-override={overrides.hotDeals}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.hotDeals
      )}
      component={Link}
      platform={"nextjs"}
    >
      <HotSvgrepoComsvgIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Whats New"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  hotDeals: ["hotDeals", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  hotDeals: "a";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDealsContainerLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDealsContainerLink__VariantsArgs;
    args?: PlasmicDealsContainerLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDealsContainerLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDealsContainerLink__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDealsContainerLink__ArgProps,
          internalVariantPropNames: PlasmicDealsContainerLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDealsContainerLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "hotDeals") {
    func.displayName = "PlasmicDealsContainerLink";
  } else {
    func.displayName = `PlasmicDealsContainerLink.${nodeName}`;
  }
  return func;
}

export const PlasmicDealsContainerLink = Object.assign(
  // Top-level PlasmicDealsContainerLink renders the root element
  makeNodeComponent("hotDeals"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicDealsContainerLink
    internalVariantProps: PlasmicDealsContainerLink__VariantProps,
    internalArgProps: PlasmicDealsContainerLink__ArgProps
  }
);

export default PlasmicDealsContainerLink;
/* prettier-ignore-end */
