// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RiFpwPZc2Ux6gBUCfunxc
// Component: HcrFaXnDMr2A

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: fRobOPq7Dpvn/component
import Footer from "../../Footer"; // plasmic-import: u78mgfCwPbxj/component

import { ModeValue, useMode } from "./PlasmicGlobalVariant__Mode"; // plasmic-import: pQjhaJ-jelU4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 5RiFpwPZc2Ux6gBUCfunxc/projectcss
import sty from "./PlasmicPrivacyPolicy.module.css"; // plasmic-import: HcrFaXnDMr2A/css

import DividerHorizontalSvgrepoComsvgIcon from "./icons/PlasmicIcon__DividerHorizontalSvgrepoComsvg"; // plasmic-import: mjb3wMhXJz8e/icon

createPlasmicElementProxy;

export type PlasmicPrivacyPolicy__VariantMembers = {};
export type PlasmicPrivacyPolicy__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrivacyPolicy__VariantsArgs;
export const PlasmicPrivacyPolicy__VariantProps = new Array<VariantPropType>();

export type PlasmicPrivacyPolicy__ArgsType = {};
type ArgPropType = keyof PlasmicPrivacyPolicy__ArgsType;
export const PlasmicPrivacyPolicy__ArgProps = new Array<ArgPropType>();

export type PlasmicPrivacyPolicy__OverridesType = {
  root?: Flex__<"div">;
  main?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  breadcrumbs?: Flex__<"div">;
  svg?: Flex__<"svg">;
  h4?: Flex__<"h4">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultPrivacyPolicyProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPrivacyPolicy__RenderFunc(props: {
  variants: PlasmicPrivacyPolicy__VariantsArgs;
  args: PlasmicPrivacyPolicy__ArgsType;
  overrides: PlasmicPrivacyPolicy__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    mode: useMode()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPrivacyPolicy.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPrivacyPolicy.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPrivacyPolicy.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root,
            {
              [projectcss.global_mode_darkMode]: hasVariant(
                globalVariants,
                "mode",
                "darkMode"
              ),
              [sty.rootglobal_mode_darkMode]: hasVariant(
                globalVariants,
                "mode",
                "darkMode"
              )
            }
          )}
        >
          <div
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(projectcss.all, sty.main, {
              [sty.mainglobal_mode_darkMode]: hasVariant(
                globalVariants,
                "mode",
                "darkMode"
              )
            })}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div
              className={classNames(projectcss.all, sty.freeBox__mBoT, {
                [sty.freeBoxglobal_mode_darkMode__mBoTMcwt]: hasVariant(
                  globalVariants,
                  "mode",
                  "darkMode"
                )
              })}
            >
              <div
                data-plasmic-name={"breadcrumbs"}
                data-plasmic-override={overrides.breadcrumbs}
                className={classNames(projectcss.all, sty.breadcrumbs, {
                  [sty.breadcrumbsglobal_mode_darkMode]: hasVariant(
                    globalVariants,
                    "mode",
                    "darkMode"
                  )
                })}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___6Pcbf,
                    {
                      [sty.linkglobal_mode_darkMode___6PcbfMcwt]: hasVariant(
                        globalVariants,
                        "mode",
                        "darkMode"
                      )
                    }
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Home"}
                </PlasmicLink__>
                <DividerHorizontalSvgrepoComsvgIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg, {
                    [sty.svgglobal_mode_darkMode]: hasVariant(
                      globalVariants,
                      "mode",
                      "darkMode"
                    )
                  })}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tnDK,
                    {
                      [sty.textglobal_mode_darkMode__tnDKMcwt]: hasVariant(
                        globalVariants,
                        "mode",
                        "darkMode"
                      )
                    }
                  )}
                >
                  {"Account"}
                </div>
              </div>
              <h4
                data-plasmic-name={"h4"}
                data-plasmic-override={overrides.h4}
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4,
                  {
                    [sty.h4global_mode_darkMode]: hasVariant(
                      globalVariants,
                      "mode",
                      "darkMode"
                    )
                  }
                )}
              >
                {"Privacy Policy"}
              </h4>
              <div className={classNames(projectcss.all, sty.freeBox__lxDjt)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yyEQh,
                    {
                      [sty.textglobal_mode_darkMode__yyEQhMcwt]: hasVariant(
                        globalVariants,
                        "mode",
                        "darkMode"
                      )
                    }
                  )}
                >
                  {
                    "At Kitabu, we prioritize the protection of our customers' privacy. This Privacy Policy delineates the manner in which we gather, utilize, and safeguard personal information when individuals engage with our online bookstore."
                  }
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bAz4L)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__orb9J,
                      {
                        [sty.h6global_mode_darkMode__orb9JMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"1. Collection of Information:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul___1Xei,
                      {
                        [sty.ulglobal_mode_darkMode___1XeiMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__vSr6K,
                        {
                          [sty.liglobal_mode_darkMode__vSr6KMcwt]: hasVariant(
                            globalVariants,
                            "mode",
                            "darkMode"
                          )
                        }
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lrYcT
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xzO1,
                            {
                              [sty.textglobal_mode_darkMode__xzO1Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Personal Data:"}
                            </span>
                            <React.Fragment>
                              {
                                " Upon registration with Kitabu, we may collect personal details including but not limited to name, email address, shipping address, and payment particulars."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__xs6I0
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6HeIp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__flBfS,
                            {
                              [sty.textglobal_mode_darkMode__flBfSMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Browsing Data"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {":"}
                            </span>
                            <React.Fragment>
                              {
                                " Non-personal information such as IP address, browser type, operating system, and browsing behaviors on our platform may be gathered."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li___0Pq1E
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lLznf
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hQzSh,
                            {
                              [sty.textglobal_mode_darkMode__hQzShMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Cookies: "}
                            </span>
                            <React.Fragment>
                              {
                                "Kitabu utilizes cookies to enhance user experience and monitor website usage patterns. Cookie preferences can be managed via browser settings."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__aonyl)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__hClwO,
                      {
                        [sty.h6global_mode_darkMode__hClwOMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"2. Utilization of Information:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__flqXn,
                      {
                        [sty.ulglobal_mode_darkMode__flqXnMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li___8DkGo
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pwK5K
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__x9DFu,
                            {
                              [sty.textglobal_mode_darkMode__x9DFuMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Order Management:"}
                            </span>
                            <React.Fragment>
                              {
                                " Personal data is utilized for order processing, facilitating purchases, and delivering products to customers."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li___9JOfj
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xOsAh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jOlK6,
                            {
                              [sty.textglobal_mode_darkMode__jOlK6Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Communication:"}
                            </span>
                            <React.Fragment>
                              {
                                " Contact information may be used for order-related correspondence, customer support, and dissemination of promotional materials or newsletters if consent is provided."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li___4Vsiw
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___31Jb0
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gb3L0,
                            {
                              [sty.textglobal_mode_darkMode__gb3L0Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Enhancement of Services: "}
                            </span>
                            <React.Fragment>
                              {
                                "Analysis of browsing data and customer feedback is instrumental in refining our website, products, and services."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7H3Pu)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__bGf0K,
                      {
                        [sty.h6global_mode_darkMode__bGf0KMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"3. Data Security:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__tlvzg,
                      {
                        [sty.ulglobal_mode_darkMode__tlvzgMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__i6L
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__j406R
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vnrY3,
                            {
                              [sty.textglobal_mode_darkMode__vnrY3Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Secure Transactions:"}
                            </span>
                            <React.Fragment>
                              {
                                " Industry-standard security protocols are employed to safeguard personal and financial information during transactions."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__vyz3Z
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lToOl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ljrFq,
                            {
                              [sty.textglobal_mode_darkMode__ljrFqMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Encryption: "}
                            </span>
                            <React.Fragment>
                              {
                                "Data encryption technologies are utilized to protect information during transmission."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__auSje
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bt0Sg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0UGiA,
                            {
                              [sty.textglobal_mode_darkMode___0UGiAMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Access Management:"}
                            </span>
                            <React.Fragment>
                              {
                                " Access to personal data is restricted to authorized personnel exclusively."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__npYl1)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__hB8Ma,
                      {
                        [sty.h6global_mode_darkMode__hB8MaMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"4. Third-Party Services:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__zxOdz,
                      {
                        [sty.ulglobal_mode_darkMode__zxOdzMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__kBvfK
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jWkkg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ltygD,
                            {
                              [sty.textglobal_mode_darkMode__ltygDMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Service Providers:"}
                            </span>
                            <React.Fragment>
                              {
                                " Kitabu may engage third-party service providers to aid in order processing, payment processing, shipping, and marketing endeavors. These entities are contractually bound to protect user information and employ it solely for designated purposes."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__erWnF
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ttOWx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jSvA,
                            {
                              [sty.textglobal_mode_darkMode__jSvAMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Third-Party Links:"}
                            </span>
                            <React.Fragment>
                              {
                                " While our website may feature links to third-party websites, Kitabu assumes no responsibility for the privacy practices or content of such sites."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nYrAs)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__baJd6,
                      {
                        [sty.h6global_mode_darkMode__baJd6Mcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"5. Children's Privacy:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__lZiT,
                      {
                        [sty.ulglobal_mode_darkMode__lZiTMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__knfE5
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1PTcK
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w43M,
                            {
                              [sty.textglobal_mode_darkMode__w43MMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          {
                            "Kitabu caters to a general audience and is not directed towards individuals under the age of 13. We do not knowingly collect personal information from minors."
                          }
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___5M9P)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__qzeQa,
                      {
                        [sty.h6global_mode_darkMode__qzeQaMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"6. User Privacy Preferences:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__at0Bu,
                      {
                        [sty.ulglobal_mode_darkMode__at0BuMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__hsJa
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__e0Ce7
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gvxAo,
                            {
                              [sty.textglobal_mode_darkMode__gvxAoMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Account Management:"}
                            </span>
                            <React.Fragment>
                              {
                                " Users retain the ability to review and update account details via the Kitabu website."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__rUnnu
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2SOyn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__e8X86,
                            {
                              [sty.textglobal_mode_darkMode__e8X86Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Communication Settings:"}
                            </span>
                            <React.Fragment>
                              {
                                " Opting in or out of promotional emails and newsletters from Kitabu is at the discretion of the user."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__kEiz
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__joKyg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fHhs0,
                            {
                              [sty.textglobal_mode_darkMode__fHhs0Mcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Cookie Management:"}
                            </span>
                            <React.Fragment>
                              {
                                " Users can adjust cookie preferences through browser settings."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pXmA)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__psg,
                      {
                        [sty.h6global_mode_darkMode__psgMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"7. Amendments to Privacy Policy:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul___0Oag0,
                      {
                        [sty.ulglobal_mode_darkMode___0Oag0Mcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__pUpih
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3Gr67
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p3Zmf,
                            {
                              [sty.textglobal_mode_darkMode__p3ZmfMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          {
                            "Kitabu reserves the right to modify this Privacy Policy at any juncture. Users will be notified of any alterations through publication of the revised policy on our website."
                          }
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xGmLy)}
                >
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__l35Iz,
                      {
                        [sty.h6global_mode_darkMode__l35IzMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    {"8. Contact Information:"}
                  </h6>
                  <Stack__
                    as={"ul"}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__lxPtg,
                      {
                        [sty.ulglobal_mode_darkMode__lxPtgMcwt]: hasVariant(
                          globalVariants,
                          "mode",
                          "darkMode"
                        )
                      }
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        sty.li__zsta
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ff0DA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rnmE,
                            {
                              [sty.textglobal_mode_darkMode__rnmEMcwt]:
                                hasVariant(globalVariants, "mode", "darkMode")
                            }
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {
                                "For inquiries or concerns regarding this Privacy Policy or personal information management, please reach out to us at "
                              }
                            </React.Fragment>
                            {
                              <PlasmicLink__
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  projectcss.__wab_text,
                                  projectcss.plasmic_default__inline,
                                  sty.link___6YXpy
                                )}
                                component={Link}
                                href={"mailto:contact@kitabu.ke"}
                                platform={"nextjs"}
                              >
                                {"contact@kitabu.ke"}
                              </PlasmicLink__>
                            }
                            <React.Fragment>{"."}</React.Fragment>
                          </React.Fragment>
                        </div>
                      </div>
                    </li>
                  </Stack__>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rmLbi,
                    {
                      [sty.textglobal_mode_darkMode__rmLbiMcwt]: hasVariant(
                        globalVariants,
                        "mode",
                        "darkMode"
                      )
                    }
                  )}
                >
                  {
                    "By utilizing the Kitabu website, users consent to the collection and utilization of their personal information in accordance with this Privacy Policy."
                  }
                </div>
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "main", "navbar", "breadcrumbs", "svg", "h4", "footer"],
  main: ["main", "navbar", "breadcrumbs", "svg", "h4"],
  navbar: ["navbar"],
  breadcrumbs: ["breadcrumbs", "svg"],
  svg: ["svg"],
  h4: ["h4"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  main: "div";
  navbar: typeof Navbar;
  breadcrumbs: "div";
  svg: "svg";
  h4: "h4";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrivacyPolicy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrivacyPolicy__VariantsArgs;
    args?: PlasmicPrivacyPolicy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPrivacyPolicy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPrivacyPolicy__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrivacyPolicy__ArgProps,
          internalVariantPropNames: PlasmicPrivacyPolicy__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrivacyPolicy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrivacyPolicy";
  } else {
    func.displayName = `PlasmicPrivacyPolicy.${nodeName}`;
  }
  return func;
}

export const PlasmicPrivacyPolicy = Object.assign(
  // Top-level PlasmicPrivacyPolicy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    main: makeNodeComponent("main"),
    navbar: makeNodeComponent("navbar"),
    breadcrumbs: makeNodeComponent("breadcrumbs"),
    svg: makeNodeComponent("svg"),
    h4: makeNodeComponent("h4"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicPrivacyPolicy
    internalVariantProps: PlasmicPrivacyPolicy__VariantProps,
    internalArgProps: PlasmicPrivacyPolicy__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Privacy Policy - Kitabu.ke",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPrivacyPolicy;
/* prettier-ignore-end */
